version: "3.3"

services:
  web:
    image: "singhsharad533/book-service:latest"
    container_name: books-api
    ports:
      - "8000:8000"
    environment:
      API_KEY: "sharad123"

    volumes:
      - ./books.db:/data/books.db   # mount your SQLite DB
